# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: validate-specs
        name: Validate YAML Specifications
        entry: python validate_all.py
        language: system
        types: [yaml]
        pass_filenames: false
